Repository jaibhedia/ChainzRegistry, pull requests merged in 2024-06, with the labels that each got.

#41 Removed the UI overflow on main page and Wallet Connect page
  lib/constant/constants.dart
  lib/screens/home_page.dart
  lib/screens/wallet_connect.dart
  lib/widget/header.dart
  lib/widget/homePageDecription.dart
  pubspec.lock
  pubspec.yaml
  src/contracts/Land.json
  src/contracts/Migrations.json
Labels: enhancement, gssoc, Level 1

#55 logo added in the header
  web/icons/logo.png
  web/index.html
Labels: enhancement, good first issue, gssoc, level1

#51 added workflow for closing old issues
  .github/workflows/close-old-issue.yml
Labels: enhancement, gssoc, level1
